---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.login.concierge.pinniped.dev
  labels:
    {{- include "concierge.labels" . | nindent 4 }}
spec:
  version: v1alpha1
  group: login.concierge.pinniped.dev
  groupPriorityMinimum: 9900
  versionPriority: 15
  service:
    name: {{ include "concierge.apiServiceName" . }}
    namespace: {{ .Release.Namespace | quote }}
    port: 443
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.identity.concierge.pinniped.dev
  labels:
    {{- include "concierge.labels" . | nindent 4 }}
spec:
  version: v1alpha1
  group: identity.concierge.pinniped.dev
  groupPriorityMinimum: 9900
  versionPriority: 15
  service:
    name: {{ include "concierge.apiServiceName" . }}
    namespace: {{ .Release.Namespace | quote }}
    port: 443