kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "concierge.aggregatedApiName" . }}
  labels:
    {{- include "concierge.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "concierge.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: {{ include "concierge.aggregatedApiName" . }}
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "concierge.impersonationProxyName" . }}
  labels:
    {{- include "concierge.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "concierge.impersonateServiceAccountName" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: pinniped-concierge-impersonation-proxy
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "concierge.kubeCertAgentName" . }}
  labels:
    {{- include "concierge.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "concierge.kubeCertAgentName" . }}
roleRef:
  kind: Role
  name: {{ include "concierge.kubeCertAgentName" . }}
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "concierge.aggregatedApiName" . }}
  labels:
    {{- include "concierge.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "concierge.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "concierge.aggregatedApiName" . }}
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pinniped-concierge-pre-authn-apis
  labels:
    {{- include "concierge.labels" . | nindent 4 }}
subjects:
  - kind: Group
    name: system:authenticated
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: system:unauthenticated
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pinniped-concierge-pre-authn-apis
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pinniped-concierge-auth-delegator
  labels:
    {{- include "concierge.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "concierge.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pinniped-concierge-cluster-info-lister-watcher
  namespace: kube-public
  labels:
    {{- include "concierge.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "concierge.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: pinniped-concierge-cluster-info-lister-watcher
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pinniped-concierge-kube-system-pod-read
  namespace: kube-system
  labels:
    {{- include "concierge.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "concierge.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: ClusterRole
  name: pinniped-concierge-kube-system-pod-read
  apiGroup: rbac.authorization.k8s.io

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pinniped-concierge-extension-apiserver-authentication-reader
  namespace: kube-system
  labels:
    {{- include "concierge.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "concierge.fullname" . }}
    namespace: {{ .Release.Namespace | quote }}
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io
---