apiVersion: v1
kind: Service
metadata:
  name: {{ include "concierge.proxyServiceName" . }}
  labels:
    {{- include "concierge.labels" . | nindent 4 }}
  annotations:
    kapp.k14s.io/disable-default-label-scoping-rules: ""
spec:
  type: ClusterIP
  selector:
    {{- include "concierge.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.proxy.service.port }}
      targetPort: proxy
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "concierge.apiServiceName" . }}
  labels:
    {{- include "concierge.labels" . | nindent 4 }}
  annotations:
    kapp.k14s.io/disable-default-label-scoping-rules: ""
spec:
  type: ClusterIP
  selector:
    {{- include "concierge.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.api.service.port }}
      targetPort: api