apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "concierge.fullname" . }}
  labels:
    app: pinniped-concierge
    {{- include "concierge.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "concierge.kubeCertAgentName" . }}
  labels:
    app: pinniped-concierge
    {{- include "concierge.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "concierge.impersonateServiceAccountName" . }}
  labels:
    app: pinniped-concierge
    {{- include "concierge.labels" . | nindent 4 }}
  annotations:
    kapp.k14s.io/change-group: impersonation-proxy.concierge.pinniped.dev/serviceaccount
secrets:
  - name: {{ include "concierge.impersonationProxyName" . }}
---