apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "exporter-unifi-protect.fullname" . }}
  labels:
    {{- include "exporter-unifi-protect.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "exporter-unifi-protect.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "exporter-unifi-protect.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "exporter-unifi-protect.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: exporter
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "exporter-unifi-protect.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - serve
          env:
            - name: UNIFI_HOST
              value: {{ required "unifiProtect.address is required" .Values.unifiProtect.address | quote }}
            - name: UNIFI_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "exporter-unifi-protect.secretName" . }}
                  key: {{ .Values.unifiProtect.existingSecretUsernameKey }}
            - name: UNIFI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "exporter-unifi-protect.secretName" . }}
                  key: {{ .Values.unifiProtect.existingSecretPasswordKey }}
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.metrics.path }}
              port: metrics
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: {{ .Values.metrics.path }}
              port: metrics
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
