image:
  repository: ghcr.io/merlindorin/exporter-unifi-protect
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65534
  fsGroup: 65534

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 9090
  annotations: {}

unifiProtect:
  address: ""
  port: 443
  username: ""
  password: ""
  existingSecret: ""
  existingSecretUsernameKey: "username"
  existingSecretPasswordKey: "password"
  insecureSkipVerify: false

metrics:
  path: /metrics
  scrapeInterval: 30s

serviceMonitor:
  enabled: false
  namespace: ""
  interval: 30s
  scrapeTimeout: 10s
  labels: {}
  annotations: {}

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
