{{-  $tagVersion := printf "v%s" .Chart.AppVersion -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "supervisor.staticConfigName" . }}
  labels:
    {{- include "supervisor.labels" . | nindent 4 }}
data:
  pinniped.yaml: |+
    apiGroupSuffix: pinniped.dev
    names:
      defaultTLSCertificateSecret: {{ include "supervisor.defaultCertificateName" . }}
    labels:
    {{- include "supervisor.labels" . | nindent 6 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supervisor.fullname" . }}
  labels:
    {{- include "supervisor.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "supervisor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supervisor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "supervisor.fullname" . }}
      containers:
        - name: {{ include "supervisor.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default $tagVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - pinniped-supervisor
            - /etc/podinfo
            - /etc/config/pinniped.yaml
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
              readOnly: true
            - name: podinfo
              mountPath: /etc/podinfo
              readOnly: true
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
            - containerPort: 8443
              protocol: TCP
              name: https
          env: []
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            initialDelaySeconds: 2
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            initialDelaySeconds: 2
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "supervisor.staticConfigName" . }}
        - name: podinfo
          downwardAPI:
            items:
              - path: labels
                fieldRef:
                  fieldPath: metadata.labels
              - path: namespace
                fieldRef:
                  fieldPath: metadata.namespace
              - path: name
                fieldRef:
                  fieldPath: metadata.name
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

