apiVersion: v1
kind: Service
metadata:
  name: {{ include "supervisor.fullname" . }}
  labels:
    {{- include "supervisor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "supervisor.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: https
      name: https