---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "supervisor.fullname" . }}
  labels:
    {{- include "supervisor.labels" . | nindent 4 }}
    app: pinniped-supervisor

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "supervisor.fullname" . }}
  labels:
    {{- include "supervisor.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "supervisor.fullname" . }}
roleRef:
  kind: Role
  name: {{ include "supervisor.fullname" . }}
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "supervisor.fullname" . }}
  labels:
    {{- include "supervisor.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - delete
  - apiGroups:
      - config.supervisor.pinniped.dev
    resources:
      - federationdomains
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - config.supervisor.pinniped.dev
    resources:
      - federationdomains/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - idp.supervisor.pinniped.dev
    resources:
      - oidcidentityproviders
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - idp.supervisor.pinniped.dev
    resources:
      - oidcidentityproviders/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - idp.supervisor.pinniped.dev
    resources:
      - ldapidentityproviders
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - idp.supervisor.pinniped.dev
    resources:
      - ldapidentityproviders/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - idp.supervisor.pinniped.dev
    resources:
      - activedirectoryidentityproviders
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - idp.supervisor.pinniped.dev
    resources:
      - activedirectoryidentityproviders/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - replicasets
      - deployments
    verbs:
      - get
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update